FROM node:16.14-alpine

LABEL version="1.0"
LABEL description="React Frontend for the Real Estate API"

WORKDIR /app

COPY ./package*.json ./

RUN npm install

# Copy all files from client to the container
COPY . .

RUN chmod 777 /app/node_modules

CMD ["npm", "run", "dev"]
